export const GOOGLE_MAP_KEY = "AIzaSyArU8uSLFz-bJIUY_jWrYz7SRKHw2pPUuU";
export const FOURSQUARE_CLIENT_ID = "CPSJIZVAFMU5TYHY01C2VNSZOJHZLWSVLUOOVLQYITJL250O";
export const FOURSQUARE_CLIENT_SECRET = "BOTQMEKLZJKEIBT0UYJKOBLP1FCXPMLVZNFTP4SGKFRP0QZX";
